set(LIB_NAMES PhysX_64 PhysXPvdSDK_static_64 PhysXCommon_64)
set(PATH_NAMES PxActor.h)

find_path(Physx_INCLUDE_DIR NAMES PxActor.h PATHS "${Physx_DIR}/PhysX/include" "${Physx_DIR}/PxShared/include")
message("CMAKE_BUILD_TYPE : ${CMAKE_BUILD_TYPE}")
foreach(LIB ${LIB_NAMES})
    find_library(Physx_LIBRARY_${LIB} NAMES ${LIB} PATHS "${Physx_DIR}/PhysX/bin/win.x86_64.vc142.mt/${CMAKE_BUILD_TYPE}")
    if(Physx_LIBRARIES)
        list(APPEND Physx_LIBRARIES "${Physx_LIBRARY_${LIB}}")
    else()
        set(Physx_LIBRARIES "${Physx_LIBRARY_${LIB}}")
    endif()
endforeach()

set(Physx_INCLUDE_DIRS ${Physx_INCLUDE_DIR})
list(APPEND Physx_INCLUDE_DIRS "${Physx_DIR}/PxShared/include")
message("Physx_INCLUDE_DIRS : ${Physx_INCLUDE_DIRS}")
if (Physx_INCLUDE_DIR AND Physx_LIBRARIES)
    set(Physx_FOUND TRUE)
endif()